### ISSUE TITLE
SSH tunnel is not working

### ISSUE THREAD

**Issue by Halama** [keboola/db-extractor-firebird#3]
![image](https://user-images.githubusercontent.com/903531/27076245-f6bafd04-502c-11e7-961b-f59b929ce6ba.png)

**Comment by Halama** [comment]
Myslím že bude stačit když tu možnost odebereme z UI.

**Comment by Halama** [comment]
https://connection.keboola.com/admin/projects/2703/extractors/keboola.ex-db-firebird/288076720/credentials

**Comment by ErikZigo** [comment]
Vyhodil jsem to z ui https://github.com/keboola/kbc-ui/pull/1241

Opravdu to nefunguje. Kdyz to nekdo bude chtit, tak to asi nebude problem dodelat. Jen se bude muset z dbname vyparsovat port, aby bylo na co namapovat ssh tunel
