### ISSUE TITLE
Prázdný result

### ISSUE THREAD

**Issue by padak** [keboola/db-extractor-firebird#4]
Pokud je odpověď prázdná, končí extraktor errorem.

```
Found orphaned table manifest: 'in.c-ex-mrp-today.zakazky.csv.manifest'
ExceptionId docker-4f9ba387f0f97fae6a496009f118a120
```

zdroj: https://connection.keboola.com/admin/projects/1085/jobs/325242968?q=

**Comment by ErikZigo** [comment]
Hotovo, do ticketu jsem napsal
